//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::{entity::prelude::*, Set};
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "message")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub date: DateTimeUtc,
    pub subject: String,
    #[sea_orm(column_type = "Text")]
    pub body: String,
    pub snippet: String,
    #[sea_orm(column_type = "Text")]
    pub clean_text: String,
    pub clean_text_tokens_in: i32,
    pub clean_text_tokens_out: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {
    fn new() -> Self {
        Self {
            id: Set(Uuid::new_v4()),
            ..ActiveModelTrait::default()
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct Message {
    pub id: Uuid,
    pub date: DateTimeUtc,
    pub subject: String,
    pub body: String,
    pub snippet: String,
    pub clean_text: String,
    pub clean_text_tokens_in: i32,
    pub clean_text_tokens_out: i32,
}

impl Message {
    pub fn into_active_model(self) -> ActiveModel {
        ActiveModel {
            id: Set(self.id),
            date: Set(self.date),
            subject: Set(self.subject),
            body: Set(self.body),
            snippet: Set(self.snippet),
            clean_text: Set(self.clean_text),
            clean_text_tokens_in: Set(self.clean_text_tokens_in),
            clean_text_tokens_out: Set(self.clean_text_tokens_out),
        }
    }
}
